spring.datasource.url=${AHNI_DB_URL}
spring.datasource.username=${AHNI_DB_USERNAME}
spring.datasource.password=${AHNI_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
