spring.application.name=ahni-backend
spring.jpa.open-in-view=false
spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true