spring.datasource.url=${AHNI_DEV_DB_URL}
spring.datasource.username=${AHNI_DEV_DB_USERNAME}
spring.datasource.password=${AHNI_DEV_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=true

