CREATE TABLE public.course (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    department_id bigint,
    code varchar(30) NOT NULL,
    name varchar(200) COLLATE ahni_korean NOT NULL,
    credit numeric(4,1) NOT NULL,
    category varchar(30) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uk_course_entity_id
        UNIQUE (entity_id),

    CONSTRAINT uk_course_code
        UNIQUE (code),

    CONSTRAINT fk_course_department
        FOREIGN KEY (department_id)
            REFERENCES public.department (id),

    CONSTRAINT ck_course_code_uppercase
        CHECK (code = upper(code)),

    CONSTRAINT ck_course_credit
        CHECK (credit >= 0.0 AND credit <= 30.0),

    CONSTRAINT ck_course_category
        CHECK (
            category IN (
                'MAJOR',
                'GENERAL_EDUCATION',
                'ELECTIVE'
            )
        ),

    CONSTRAINT ck_course_major_department
        CHECK (category <> 'MAJOR' OR department_id IS NOT NULL)
);

CREATE INDEX idx_course_department
    ON public.course (department_id);

CREATE INDEX idx_course_active_category
    ON public.course (is_active, category);
