CREATE TABLE public.student_grade (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id bigint NOT NULL,
    course_id bigint NOT NULL,
    academic_year smallint NOT NULL,
    term varchar(20) NOT NULL,
    grade_code varchar(20),
    grade_point numeric(3,2),
    credit numeric(4,1) NOT NULL,
    is_rpl boolean NOT NULL DEFAULT false,
    is_retake boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uk_student_grade_entity_id
        UNIQUE (entity_id),

    CONSTRAINT uk_student_grade_attempt
        UNIQUE (student_id, course_id, academic_year, term),

    CONSTRAINT fk_student_grade_student
        FOREIGN KEY (student_id)
            REFERENCES public.student (id),

    CONSTRAINT fk_student_grade_course
        FOREIGN KEY (course_id)
            REFERENCES public.course (id),

    CONSTRAINT ck_student_grade_academic_year
        CHECK (academic_year BETWEEN 2000 AND 9999),

    CONSTRAINT ck_student_grade_term
        CHECK (term IN ('FIRST', 'SUMMER', 'SECOND', 'WINTER')),

    CONSTRAINT ck_student_grade_code
        CHECK (
            grade_code IS NULL OR grade_code IN (
                'A_PLUS',
                'A_ZERO',
                'B_PLUS',
                'B_ZERO',
                'C_PLUS',
                'C_ZERO',
                'D_PLUS',
                'D_ZERO',
                'F',
                'P',
                'NP'
            )
        ),

    CONSTRAINT ck_student_grade_point
        CHECK (
            grade_point IS NULL
            OR grade_point BETWEEN 0.00 AND 4.50
        ),

    CONSTRAINT ck_student_grade_credit
        CHECK (credit > 0.0 AND credit <= 30.0),

    CONSTRAINT ck_student_grade_state
        CHECK (
            (
                is_rpl
                AND grade_code IS NULL
                AND grade_point IS NULL
            )
            OR
            (
                NOT is_rpl
                AND grade_code IN ('P', 'NP')
                AND grade_point IS NULL
            )
            OR
            (
                NOT is_rpl
                AND grade_code IN (
                    'A_PLUS',
                    'A_ZERO',
                    'B_PLUS',
                    'B_ZERO',
                    'C_PLUS',
                    'C_ZERO',
                    'D_PLUS',
                    'D_ZERO',
                    'F'
                )
                AND grade_point IS NOT NULL
            )
        )
);

CREATE INDEX idx_student_grade_student
    ON public.student_grade (student_id);

CREATE INDEX idx_student_grade_course
    ON public.student_grade (course_id);
