CREATE TABLE public.graduation_requirement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    department_id bigint NOT NULL,
    admission_year integer NOT NULL,
    major_type varchar(30) NOT NULL,
    min_total_credit numeric(5,1) NOT NULL,
    min_major_credit numeric(5,1) NOT NULL,
    min_double_major_credit numeric(5,1) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uk_graduation_requirement_entity_id
        UNIQUE (entity_id),

    CONSTRAINT uk_graduation_requirement_policy
        UNIQUE (department_id, admission_year, major_type),

    CONSTRAINT fk_graduation_requirement_department
        FOREIGN KEY (department_id)
            REFERENCES public.department (id),

    CONSTRAINT ck_graduation_requirement_admission_year
        CHECK (admission_year BETWEEN 2000 AND 9999),

    CONSTRAINT ck_graduation_requirement_major_type
        CHECK (major_type IN ('PRIMARY', 'DOUBLE_MAJOR', 'MINOR')),

    CONSTRAINT ck_graduation_requirement_total_credit
        CHECK (min_total_credit >= 0.0),

    CONSTRAINT ck_graduation_requirement_major_credit
        CHECK (min_major_credit >= 0.0),

    CONSTRAINT ck_graduation_requirement_double_major_credit
        CHECK (min_double_major_credit >= 0.0)
);

CREATE INDEX idx_graduation_requirement_department
    ON public.graduation_requirement (department_id);
