CREATE TABLE public.required_course (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    graduation_requirement_id bigint NOT NULL,
    course_id bigint NOT NULL,
    category varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_required_course_entity_id UNIQUE (entity_id),
    CONSTRAINT fk_required_course_graduation_requirement
        FOREIGN KEY (graduation_requirement_id)
        REFERENCES public.graduation_requirement (id),
    CONSTRAINT fk_required_course_course
        FOREIGN KEY (course_id)
        REFERENCES public.course (id),
    CONSTRAINT ck_required_course_category
        CHECK (category IN ('MAJOR_FOUNDATION', 'MAJOR_REQUIRED', 'GENERAL_REQUIRED'))
);

CREATE UNIQUE INDEX uk_required_course_active_assignment
    ON public.required_course (graduation_requirement_id, course_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_required_course_active_requirement
    ON public.required_course (graduation_requirement_id)
    WHERE deleted_at IS NULL;
