CREATE TABLE public.curriculum (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    department_id bigint NOT NULL REFERENCES public.department(id),
    curriculum_year integer NOT NULL CHECK (curriculum_year BETWEEN 2000 AND 9999),
    source_title varchar(200) NOT NULL CHECK (btrim(source_title) <> ''),
    source_url varchar(2048),
    published boolean NOT NULL DEFAULT false,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_curriculum_department_year UNIQUE (department_id, curriculum_year)
);

CREATE TABLE public.curriculum_course (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    curriculum_id bigint NOT NULL REFERENCES public.curriculum(id),
    course_id bigint NOT NULL REFERENCES public.course(id),
    division varchar(30) NOT NULL CHECK (division IN (
        'MAJOR_REQUIRED', 'MAJOR_ELECTIVE', 'MAJOR_FOUNDATION',
        'GENERAL_REQUIRED', 'GENERAL_ELECTIVE', 'ELECTIVE'
    )),
    recommended_year integer CHECK (recommended_year BETWEEN 1 AND 6),
    recommended_term varchar(20) CHECK (recommended_term IN ('FIRST', 'SECOND', 'BOTH')),
    area_code varchar(30),
    area_name varchar(100),
    major_area varchar(100),
    note text CHECK (length(note) <= 4000),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_curriculum_course UNIQUE (curriculum_id, course_id)
);
