CREATE TABLE public.inquiry (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id bigint NOT NULL,
    title varchar(200) NOT NULL,
    content varchar(4000) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'SUBMITTED',
    answer varchar(4000),
    answered_by_admin_id bigint,
    answered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,

    CONSTRAINT uk_inquiry_entity_id
        UNIQUE (entity_id),

    CONSTRAINT fk_inquiry_student
        FOREIGN KEY (student_id)
            REFERENCES public.student (id),

    CONSTRAINT fk_inquiry_answered_by_admin
        FOREIGN KEY (answered_by_admin_id)
            REFERENCES public.admin (id),

    CONSTRAINT ck_inquiry_status
        CHECK (status IN ('SUBMITTED', 'IN_REVIEW', 'ANSWERED', 'CLOSED')),

    CONSTRAINT ck_inquiry_title_not_blank
        CHECK (length(btrim(title)) > 0),

    CONSTRAINT ck_inquiry_content_not_blank
        CHECK (length(btrim(content)) > 0),

    CONSTRAINT ck_inquiry_answer_state
        CHECK (
            (
                answer IS NULL
                AND answered_by_admin_id IS NULL
                AND answered_at IS NULL
            )
            OR
            (
                status IN ('ANSWERED', 'CLOSED')
                AND answer IS NOT NULL
                AND length(btrim(answer)) > 0
                AND answered_by_admin_id IS NOT NULL
                AND answered_at IS NOT NULL
            )
        )
);

CREATE INDEX idx_inquiry_student_created_at
    ON public.inquiry (student_id, created_at DESC);

CREATE INDEX idx_inquiry_status_created_at
    ON public.inquiry (status, created_at DESC);
