DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM student)
        OR EXISTS (SELECT 1 FROM admin)
        OR EXISTS (SELECT 1 FROM student_verification) THEN
        RAISE EXCEPTION
            'V3 migration requires empty student, admin, and student_verification tables';
END IF;
END;
$$;

DROP TABLE student_verification;
DROP TABLE admin;
DROP TABLE student;

CREATE TABLE student (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    auth_user_id uuid NOT NULL,
    department_id bigint NOT NULL,
    student_number varchar(30) NOT NULL,
    name varchar(100) NOT NULL,
    email varchar(320) NOT NULL,
    enrollment_status varchar(30) NOT NULL,
    account_status varchar(30) NOT NULL DEFAULT 'PENDING',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,

    CONSTRAINT uk_student_entity_id
     UNIQUE (entity_id),

    CONSTRAINT uk_student_auth_user_id
     UNIQUE (auth_user_id),

    CONSTRAINT uk_student_student_number
     UNIQUE (student_number),

    CONSTRAINT uk_student_email
     UNIQUE (email),

    CONSTRAINT fk_student_department
     FOREIGN KEY (department_id)
         REFERENCES department (id),

    CONSTRAINT ck_student_enrollment_status
     CHECK (
        enrollment_status IN (
          'ENROLLED',
           'LEAVE',
           'GRADUATED',
           'WITHDRAWN'
        )
     ),

    CONSTRAINT ck_student_account_status
     CHECK (
         account_status IN (
            'PENDING',
            'ACTIVE',
            'REJECTED',
            'SUSPENDED'
         )
     )
);

CREATE TABLE admin (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    auth_user_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    email varchar(320) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,

    CONSTRAINT uk_admin_entity_id
       UNIQUE (entity_id),

    CONSTRAINT uk_admin_auth_user_id
       UNIQUE (auth_user_id),

    CONSTRAINT uk_admin_email
       UNIQUE (email)
);

CREATE TABLE student_verification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id bigint NOT NULL,
    document_type varchar(40) NOT NULL,
    document_storage_key text NOT NULL,
    provider varchar(100),
    external_reference varchar(255),
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by_admin_id bigint,
    requested_at timestamptz NOT NULL DEFAULT now(),
    reviewed_at timestamptz,
    expires_at timestamptz,
    rejection_reason text,

    CONSTRAINT uk_student_verification_entity_id
      UNIQUE (entity_id),

    CONSTRAINT uk_student_verification_storage_key
      UNIQUE (document_storage_key),

    CONSTRAINT fk_student_verification_student
      FOREIGN KEY (student_id)
          REFERENCES student (id),

    CONSTRAINT fk_student_verification_admin
      FOREIGN KEY (reviewed_by_admin_id)
          REFERENCES admin (id),

    CONSTRAINT ck_student_verification_document_type
      CHECK (
          document_type IN (
            'ENROLLMENT_CERTIFICATE',
            'ACADEMIC_RECORD'
          )
      ),

    CONSTRAINT ck_student_verification_status
      CHECK (
          status IN (
             'PENDING',
             'VERIFIED',
             'REJECTED',
             'EXPIRED'
          )
      )
);

CREATE INDEX idx_student_verification_student_id
    ON student_verification (student_id);

CREATE INDEX idx_student_verification_status
    ON student_verification (status);