CREATE TABLE allowed_signup_email_domain (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain varchar(255) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_allowed_signup_email_domain_format
        CHECK (
            domain = btrim(lower(domain))
            and domain !~ '@'
            and domain ~ '^[a-z0-9.-]+$'
        )
);

ALTER TABLE allowed_signup_email_domain ENABLE ROW LEVEL SECURITY;

INSERT INTO allowed_signup_email_domain (domain) VALUES ('inha.edu');

CREATE OR replace FUNCTION public.hook_restrict_signup_by_email_domain(event jsonb) returns jsonb
       language plpgsql
       security definer
       set search_path = ''
       as $$
       declare email_value text;
               domain_value text;
       begin
            email_value := lower(btrim(event -> 'user' ->> 'email'));

            if email_value is null
               or email_value !~ '^[^@[:space:]]+@[^@[:space:]]+$'
           then
               return jsonb_build_object(
                    'error', jsonb_build_object(
                        'http_code', 400,
                        'message', 'A valid school email address is required.'
                    )
               );
           end if;

           domain_value := split_part(email_value, '@', 2);

            if exists (
               select 1
               from public.allowed_signup_email_domain allowed_domain
               where allowed_domain.domain = domain_value
            ) then
               return '{}'::jsonb;
           end if;

           return jsonb_build_object(
                'error', jsonb_build_object(
                    'http_code', 403,
                    'message', 'Only approved school email domains are allowed.'
                )
          );
      end;
      $$;

REVOKE EXECUTE ON FUNCTION public.hook_restrict_signup_by_email_domain(jsonb) from public;

do $$
begin
    if exists (
       select 1
       from pg_roles
       where rolname = 'supabase_auth_admin'
    ) then
       execute 'grant execute on function public.hook_restrict_signup_by_email_domain(jsonb) to supabase_auth_admin';
   end if;
end
$$;