CREATE TABLE public.student_major (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id bigint NOT NULL,
    department_id bigint NOT NULL,
    major_type varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,

    CONSTRAINT uk_student_major_entity_id
        UNIQUE (entity_id),

    CONSTRAINT fk_student_major_student
        FOREIGN KEY (student_id)
            REFERENCES public.student (id),

    CONSTRAINT fk_student_major_department
        FOREIGN KEY (department_id)
            REFERENCES public.department (id),

    CONSTRAINT ck_student_major_type
        CHECK (
            major_type IN (
                'PRIMARY',
                'DOUBLE_MAJOR',
                'MINOR'
            )
        )
);

-- 기존 학과는 주전공으로 이전
INSERT INTO public.student_major (
    student_id,
    department_id,
    major_type
)
SELECT
    id,
    department_id,
    'PRIMARY'
FROM public.student;

ALTER TABLE public.student
DROP CONSTRAINT fk_student_department;

ALTER TABLE public.student
DROP COLUMN department_id;

-- 동일한 전공 관계의 중복 등록 방지
CREATE UNIQUE INDEX uk_student_major_active_assignment
    ON public.student_major (
        student_id,
        department_id,
        major_type
    )
    WHERE deleted_at IS NULL;

-- 활성 주전공은 학생당 하나만 허용
CREATE UNIQUE INDEX uk_student_major_active_primary
    ON public.student_major (student_id)
    WHERE major_type = 'PRIMARY'
      AND deleted_at IS NULL;

CREATE INDEX idx_student_major_department
    ON public.student_major (department_id);
